baseURL = "https://xn--kinderbcher-zhb.projektemacher.org/"
theme = ["projektemacher-base", "blogpaper"]
title = "Kinderbücher"
languageCode = "de"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
copyright = "<a href=\"https://projektemacher.org\">Projektemacher</a>"

[params]
    navHome = "Start"
    copyrightYears = "MMXXI"
    iiifCanvasHeight = 400
    iiifCanvasWidth = 300
    productionIIIFURLPrefix="https://static.projektemacher.org/kinderbuecher/"

# navigation
[menu]
    [[menu.main]]
        name = "Über"
        URL = "about"
        weight = 1

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

[imaging]
    quality = 95

#[outputs]
#    page = ["HTML", "JSON"]

[mediaTypes]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]

  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "themes/blogpaper/assets/css/normalize.css"
        target = "assets/scss"

    [[module.mounts]]
        source = "themes/blogpaper/assets/css"
        target = "assets/scss"
