baseURL = "https://xn--kinderbcher-zhb.projektemacher.org/"
theme = ["blogpaper"]
title = "Kinderbücher"
languageCode = "de"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
    navHome = "Start"
#    Copyright = "&copy; MMXX <a href=\"https://projektemacher.org\">Projektemacher</a>"

# navigation
[menu]
    [[menu.main]]
        name = "Über"
        URL = "/about"
        weight = 1

[markup.goldmark.renderer]
  unsafe= true

[imaging]
    quality = 95

[outputs]
    page = ["HTML", "JSON"]

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

#    [[module.mounts]]
#        source = "assets/css"
#        target = "assets/css"
