# See https://github.com/marketplace/actions/todo-to-issue
name: "Run TODO to Issue"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Free some disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/.ghcup/ /usr/share/dotnet/ /opt/microsoft /usr/local/aws-* /usr/share/miniconda /opt/az /usr/share/kotlinc /usr/share/man /usr/share/sbt /usr/local/julia* /usr/share/az* /usr/share/apache-maven* /usr/share/gradle* /usr/share/swift
          df -h
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.12.2"
        with:
          AUTO_ASSIGN: true
          LANGUAGES: "https://raw.githubusercontent.com/cmahnke/projektemacher-base/main/.syntax.json"
